Fix reentrancy example
Brushfam/openbrush-contracts pull request #108
Opened 2023-07-13 08:20 UTC by prxgr4mm3r

2023-07-13 08:42 UTC, prxgr4mm3r commented on docs/docs/smart-contracts/example/data.md
I commit these changes accidentally, but anyway, it has to be rewritten completely

2023-07-13 10:25 UTC, coreggon11 requested changes
lgtm, pls add tests showing it works

2023-07-13 10:25 UTC, coreggon11 commented on examples/reentrancy_guard/contracts/flip_on_me/lib.rs
>          fn flip_on_me(&mut self) -> Result<(), ReentrancyGuardError> {
we can remove this function and call the other function directly

2023-07-20 08:51 UTC, coreggon11 submitted a review, later dismissed

2023-07-20 12:55 UTC, Artemka374 approved these changes

2023-07-20 12:55 UTC, merged