[WIP] Feature/governance
Brushfam/openbrush-contracts pull request #126
Opened 2023-08-03 11:55 UTC by varex83

2023-08-15 09:11 UTC, coreggon11 commented on contracts/src/utils/checkpoint/mod.rs
> +            let mid = low / 2 + high / 2;
if low = 1 and high = 1 average will be 0

2023-08-15 09:13 UTC, coreggon11 commented on contracts/src/utils/checkpoint/mod.rs
> +            let mid = low / 2 + high / 2;
here too

2023-08-16 20:17 UTC, coreggon11 requested changes

2023-08-17 08:29 UTC, Artemka374 commented on contracts/src/governance/governor/internal.rs
> +pub trait TimestampProvider: DefaultEnv {
we need it more for testing, cause we can't change timestamp in tests

2023-08-17 09:10 UTC, Artemka374 commented on contracts/src/traits/governance/mod.rs
> +    pub proposer: AccountId,
I think it is not needed to do default, we don't use unwrap_or_default() for these and it's better not to

2023-08-17 09:11 UTC, Artemka374 commented on Cargo.toml
> +    "mocks"
It's mock contract to test executing transactions in other contracts through governance

2023-08-17 13:48 UTC, Artemka374 commented on contracts/src/traits/governance/mod.rs
> +#[cfg_attr(feature = "std", derive(scale_info::TypeInfo, ink::storage::traits::StorageLayout))]
it does not implement scale traits, so it should be there

2023-08-24 15:17 UTC, coreggon11 commented on Cargo.toml
> +    "mocks"
it can be any contract though

2023-08-24 15:41 UTC, coreggon11 reviewed
gj, pls look at my comments

run cargo clippy on each contract and fix CI

2023-08-24 15:41 UTC, coreggon11 commented on contracts/src/governance/utils/votes/events.rs
> +        ()
no need to return () explicitly

2023-08-24 15:41 UTC, coreggon11 commented on contracts/src/governance/utils/votes/events.rs
> +        ()
no need to return () explicitly

2023-08-24 15:41 UTC, coreggon11 commented on contracts/src/governance/utils/votes/impls.rs
> +    fn get_votes(&self, account: AccountId) -> Result<Balance, GovernanceError> {
no need to return result here or?

2023-08-24 15:41 UTC, coreggon11 commented on contracts/src/governance/utils/votes/internal.rs
> +                let from_addr = from.unwrap();
```suggestion
            if let Some(from_addr) = from {
```

2023-08-24 15:41 UTC, coreggon11 commented on contracts/src/governance/utils/votes/internal.rs
> +                let to_addr = to.unwrap();
```suggestion
            if let Some(to_addr) = to {
```

2023-08-24 15:41 UTC, coreggon11 commented on contracts/src/governance/utils/votes/internal.rs
> +        Ok(self
no need to return result

2023-08-24 15:41 UTC, coreggon11 commented on contracts/src/governance/utils/votes/internal.rs
> +            .cloned()
```suggestion
        self
            .data::<Data>()
            .delegate_checkpoints
            .get(&account)
            .unwrap_or_default()
            .at(pos as usize)
            .ok_or(GovernanceError::IndexOutOfRange)
            .cloned()
```

2023-08-24 15:41 UTC, coreggon11 commented on examples/psp22_extensions/votes/lib.rs
> +    // use openbrush::{
what about these comments

2023-08-25 07:59 UTC, Artemka374 commented on LICENSE
> +// Copyright (c) 2023 Brushfam
That's how it should be, as I said, I've talked with Vova about that, and there should be added new field for every new company that is currently working on repo

2023-08-25 08:00 UTC, Artemka374 commented on contracts/src/governance/extensions/timelock_controller/mod.rs
> -pub struct CallInput<'a>(&'a [u8]);
I've moved it in governor mod, since we are using it there as well and this one is extension

2023-08-28 20:24 UTC, merged