remove `ZERO_ADDRESS` and `is_zero`, use `Option<AccountId>` instead
Brushfam/openbrush-contracts pull request #43
Opened 2023-04-17 20:43 UTC by coreggon11

Addresses [this issue](https://github.com/Brushfam/openbrush-contracts/issues/42).

TODO:
- [x] Remove `ZERO_ADDRESS` and `is_zero()`
- [x] Use `Option<AccountId> and `is_none()` where possible
- [ ] Fix unit tests
- [ ] In many places we were checking if account is zero (for example in transfers). We can either change these functions to use `Option<AccountId>` and check if `is_none()` or leave it as it is, removing this check. This makes sense IMO, since sending tokens to `None` does not really make sense (need to think about this and either leave it or change :))

2023-04-18 14:24 UTC, Artemka374 requested changes
lgtm, but take a look at comments pls

2023-04-18 14:24 UTC, Artemka374 commented on contracts/src/access/ownable/mod.rs
> +        Some(account) if account == T::env().caller() => body(instance),
may we change the syntax here to more readable?

2023-04-18 14:24 UTC, Artemka374 commented on contracts/src/traits/errors/psp22.rs
> +    ZeroAddress,
Let's call it another name, e.g. AccountDoesNotExist

2023-04-18 14:24 UTC, Artemka374 commented on contracts/src/traits/errors/timelock_controller.rs
> +    ZeroAddress,
Same here

2023-04-18 14:24 UTC, Artemka374 commented on contracts/src/traits/errors/psp22.rs
> +    ZeroAddress,
because this way, user can use zero address, so this naming of error looks strange

2023-04-25 19:17 UTC, deuszx commented
Pardon my ignorance, but wouldn't it be simpler to change the definition of `ZERO_ADDRESS`? I.e. make it something for which there is no known private key?

2023-04-25 19:22 UTC, coreggon11 commented
> Pardon my ignorance, but wouldn't it be simpler to change the definition of `ZERO_ADDRESS`? I.e. make it something for which there is no private key?

it would indeed, but it will be nicer to utilize `Option`

2023-04-25 19:26 UTC, deuszx commented
> > Pardon my ignorance, but wouldn't it be simpler to change the definition of `ZERO_ADDRESS`? I.e. make it something for which there is no private key?
> 
> it would indeed, but it will be nicer to utilize `Option`

These changes here will require every downstream consumer of the lib to heavily update their contracts though while changing the `ZERO_ADDRESS` address would require no work and still mean the same thing semantically.

2023-04-25 19:39 UTC, coreggon11 commented
> These changes here will require every downstream consumer of the lib to heavily update their contracts though while changing the `ZERO_ADDRESS` address would require no work and still mean the same thing semantically.

You can still use the previous versions in your contracts and not use the zero address. The updates in this PR and in a new version will be more rusty and clear (for example, `[1u8; 32]` as `ZERO_ADDRESS ` does not really make sense).

However, a good idea is simply changing `ZERO_ADDRESS ` to, i.e., `[1u8; 32]` in the 3.1.1 patch, not letting projects using this fall for the known private key, and release the more rusty and comprehensible updates in a 3.2.0 version.

2023-04-27 12:38 UTC, deuszx commented
There's probably already a lot of contracts that are simply Ethereum's translated to ink and b/c of that they're dependent on the fact that there exists something like a `ZERO_ADDRESS` (take for example Uniswap contract). The proposed change will require major overhaul of these contracts (which increases the likelihood of bugs).

2023-07-04 08:49 UTC, closed without merging